name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GCP Container Registry
        run: echo "${{ secrets.GCP_CREDENTIALS }}" | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker tag reverse/reverse:latest gcr.io/reverse/reverse:latest
          docker tag mysql:5.7 gcr.io/reverse/mysql:5.7
          docker push gcr.io/reverse/reverse:latest
          docker push gcr.io/reverse/mysql:5.7

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set up GCP credentials
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: reverse

      - name: Deploy to GKE
        run: |

          kubectl apply -f k8s/deployment.yaml
#          kubectl config set-cluster gke_cluster --server=https://your-gke-cluster-endpoint
        # kubectl config set-credentials gke_user --token=${{ secrets.GCP_ACCESS_TOKEN }}
          # kubectl config set-context gke_context --cluster=gke_cluster --user=gke_user
          # kubectl config use-context gke_context
