#cicd..
name: reverse-ci
#on:
#- workflow_dispatch
on:
  push:
     branches:
        - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # - name: Deploy using Google Cloud Deploy
      #   run: |
      #     # gcloud deploy releases create release-$(date +%Y%m%d-%H%M%S) \
      #     --project=reverse-ip-app \

      #     --region=us-central1 \
      #     --images=your-app=gcr.io/reverse/reverse:v1 \
      #     --description="Automated deployment from GitHub Actions"
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Docker Compose Command
        uses: blag/action-docker-compose@v0.0.1
        with:
    # Command line arguments for docker-compose
          cli-args: up -d
          push: true
          tags: gcr.io/reverse/reverse:latest
          
      
      - name: Log in to Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}

      # - name: Build & push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./docker-compose.yml # Adjusted path to Dockerfile
      #     push: true
      #     tags: gcr.io/reverse/reverse:latest
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Google GKE Helm Deployment
  # You may pin to the exact commit or the version.
  # uses: dgrezza/action-gcp-helm-deploy@0c3089cd9a2c4a940df8373991bb5024c8c80dc8
        uses: dgrezza/action-gcp-helm-deploy@v1.0.3
        with:
          # SA json key used to login to GKE.
          serviceaccount-key: ${{ secrets.GCP_CREDENTIALS }}
          # SA name used to login to GKE.
          #serviceaccount-name: devops
          # GCP region to use (default: asia-southeast1)
          gcp-region: us-central1 # default is asia-southeast1
          # GCP project to use
          gcp-project: reverse-ip-app
          # GKE cluster name.
          gke-cluster-name: reverse
          # Comma separates list of helm values files.
          # config-files: # optional
          # # Kubernetes namespace to use.
          # namespace: # optional
          # # Comma separated list of value sets for helms. e.x: key1=value1,key2=value2
          # values: # optional
          # # Name of the helm deploy.
          # name: # optional
          # # The path of the chart.
          # chart-path: # optional
          # # docker image tag for new deployment
          # image-tag: # optional
          # # application name for deployment
          application-name: reserve-ip-app
          
